---
title: "p8105_hw2_lel2176"
output: github_document
---

```{r}
library(tidyverse)
```

## Problem 2

#load in mr. trash wheel dataset and clean
```{r}
mr_trash_wheel = 
  readxl::read_excel("data/trash_data.xlsx", "Mr. Trash Wheel") |> 
  janitor::clean_names() |> 
  rename(weight = weight_tons) |> 
  rename(volume = volume_cubic_yards) |> 
  select(dumpster, date, weight, volume, plastic_bottles, polystyrene, cigarette_butts, glass_bottles, grocery_bags, chip_bags, sports_balls, homes_powered) |> 
  mutate(
    homes_powered = (weight*500) / 30 , 
    trash_wheel = "mr. trash"
  )
mr_trash_wheel
```

#load in prof. trash wheel dataset and clean
```{r}
prof_trash_wheel = 
  readxl::read_excel("data/trash_data.xlsx", "Professor Trash Wheel") |> 
  janitor::clean_names() |> 
  rename(weight = weight_tons) |> 
  rename(volume = volume_cubic_yards) |> 
  select(dumpster, date, weight, volume, plastic_bottles, polystyrene, cigarette_butts, glass_bottles, grocery_bags, chip_bags, homes_powered) |> 
  mutate(
    homes_powered = (weight*500) / 30 ,
    trash_wheel = "Prof. Trash"
  )
prof_trash_wheel
```

#load in gwynnda wheel dataset and clean
```{r}
gwyn_trash_wheel = 
  readxl::read_excel("data/trash_data.xlsx", "Gwynnda Trash Wheel") |> 
  janitor::clean_names() |> 
  rename(weight = weight_tons) |> 
  rename(volume = volume_cubic_yards) |> 
  select(dumpster, date, weight, volume, plastic_bottles, polystyrene, cigarette_butts, plastic_bags, homes_powered) |> 
  mutate(
  homes_powered = (weight*500) / 30 ,
  trash_wheel = "gwynnda trash"
)
gwyn_trash_wheel
```

# combine 3 datasets

```{r}
trash_data = 
  bind_rows(mr_trash_wheel, prof_trash_wheel, gwyn_trash_wheel)
trash_data
```

## Problem 3


```{r}

mci_baseline_data = read_csv("data/data_mci/MCI_baseline.csv")[-1,] |> 
  janitor::clean_names() |> 
  rename(ID = x1) |> 
  rename(current_age = age_at_the_study_baseline) |> 
  rename(sex = x1_male_0_female) |> 
  rename(education = years_of_education) |> 
  rename(apoe4 = x1_apoe4_carrier_0_apoe4_non_carrier) |> 
  rename(age_at_onset = age_at_the_onset_of_mci_missing_if_a_subject_remains_mci_free_during_the_follow_up_period) |> 
    mutate(
    sex = case_match(
      sex, 
      "0" ~ "male",
      "1" ~ "female"
    )
  ) |> 
    mutate(
    apoe4 = case_match(
      apoe4, 
      "1" ~ "carrier",
      "0" ~ "non-carrier"
    )
  )

baseline_data = mci_baseline_data[!(mci_baseline_data$age_at_onset=="."),]

amyloid_data = read_csv("data/data_mci/mci_amyloid.csv")[-1,] |> 
  janitor::clean_names() |> 
  rename(ID = study_id) |> 
  rename(baseline = time_in_years_elapsed_since_the_study_baseline_to_the_visit_where_biomarker_amyloid_42_40_ratio_was_measured) |> 
  rename(time_2 = na_3) |> 
  rename(time_4 = na_4) |> 
  rename(time_6 = na_5) |> 
  rename(time_8 = na_6) |> 
  drop_na()
 

baseline_data
amyloid_data

merge_data = merge(baseline_data, amyloid_data, by.baseline_data = ID, by.amyloid_data = ID)
merge_data
```



