p8105_hw2_lel2176
================

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.3     ✔ readr     2.1.4
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.0
    ## ✔ ggplot2   3.4.3     ✔ tibble    3.2.1
    ## ✔ lubridate 1.9.2     ✔ tidyr     1.3.0
    ## ✔ purrr     1.0.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

# Problem 2

### mr. trash wheel

``` r
mr_trash_wheel = 
  readxl::read_excel("data/new_trash_data.xlsx", "Mr. Trash Wheel") |> 
  janitor::clean_names() |> 
  drop_na(dumpster) |> 
  rename(weight = weight_tons) |> 
  rename(volume = volume_cubic_yards) |> 
  select(dumpster, date, weight, volume, plastic_bottles, polystyrene, cigarette_butts, glass_bottles, plastic_bags, wrappers, sports_balls, homes_powered) |> 
  mutate(
    homes_powered = (weight*500) / 30 , 
    trash_wheel = "mr. trash"
  )
```

    ## New names:
    ## • `` -> `...15`
    ## • `` -> `...16`

``` r
mr_trash_wheel
```

    ## # A tibble: 584 × 13
    ##    dumpster date                weight volume plastic_bottles polystyrene
    ##       <dbl> <dttm>               <dbl>  <dbl>           <dbl>       <dbl>
    ##  1        1 2014-05-16 00:00:00   4.31     18            1450        1820
    ##  2        2 2014-05-16 00:00:00   2.74     13            1120        1030
    ##  3        3 2014-05-16 00:00:00   3.45     15            2450        3100
    ##  4        4 2014-05-17 00:00:00   3.1      15            2380        2730
    ##  5        5 2014-05-17 00:00:00   4.06     18             980         870
    ##  6        6 2014-05-20 00:00:00   2.71     13            1430        2140
    ##  7        7 2014-05-21 00:00:00   1.91      8             910        1090
    ##  8        8 2014-05-28 00:00:00   3.7      16            3580        4310
    ##  9        9 2014-06-05 00:00:00   2.52     14            2400        2790
    ## 10       10 2014-06-11 00:00:00   3.76     18            1340        1730
    ## # ℹ 574 more rows
    ## # ℹ 7 more variables: cigarette_butts <dbl>, glass_bottles <dbl>,
    ## #   plastic_bags <dbl>, wrappers <dbl>, sports_balls <dbl>,
    ## #   homes_powered <dbl>, trash_wheel <chr>

`mr_trash_wheel` is a dataset with 584 dumpsters and 13 variables. the
variables provide information on all of the observed dumpsters which are
labeled by their dumpster number `dumpster` and the date `date`. each
dumpster has recorded measures of their `weight` (measure in tons),
`volume` (measured by cubic yards), specific numbers of each type of
trash they contain, and the number of homes they have powered calculated
by `homes_powered = (weight*500) / 30` since each ton of trash equates
500 kilowatts of energy and an average household uses 30 kilowatts per
day. the last row of `mr_trash_wheel` was deleted because it was missing
values for `dumpster` and `date`. the variable names were renamed in
order to be easier to read and comprehend. the original variable columns
`month` and `year` were removed since the date is already provided. the
original variable column `homes_powered` was mutated in order to
correctly calculate the number of homes powered by mr. trash wheel.
lastly, a variable column `trash_wheel` was added in order to specify
that these observed dumpsters belong to mr. trash wheel.

### professor trash wheel

``` r
prof_trash_wheel = 
  readxl::read_excel("data/new_trash_data.xlsx", "Professor Trash Wheel") |> 
  janitor::clean_names() |> 
  drop_na(dumpster, plastic_bottles) |> 
  rename(weight = weight_tons) |> 
  rename(volume = volume_cubic_yards) |> 
  select(dumpster, date, weight, volume, plastic_bottles, polystyrene, cigarette_butts, glass_bottles, plastic_bags, wrappers, homes_powered) |> 
  mutate(
    homes_powered = (weight*500) / 30 ,
    trash_wheel = "Prof. Trash"
  )
prof_trash_wheel
```

    ## # A tibble: 105 × 12
    ##    dumpster date                weight volume plastic_bottles polystyrene
    ##       <dbl> <dttm>               <dbl>  <dbl>           <dbl>       <dbl>
    ##  1        1 2017-01-02 00:00:00   1.79     15            1950        6080
    ##  2        2 2017-01-30 00:00:00   1.58     15            9540       11230
    ##  3        3 2017-02-26 00:00:00   2.32     18            8350        9210
    ##  4        4 2017-02-26 00:00:00   3.72     15            8590        1030
    ##  5        5 2017-02-28 00:00:00   1.45     15            7830        9950
    ##  6        6 2017-03-30 00:00:00   1.71     15            8210       10340
    ##  7        7 2017-04-01 00:00:00   1.82     15            9830       11020
    ##  8        8 2017-04-20 00:00:00   2.37     15            9240        8760
    ##  9        9 2017-05-10 00:00:00   2.64     15            9540        8810
    ## 10       10 2017-05-26 00:00:00   2.78     15            8230        7800
    ## # ℹ 95 more rows
    ## # ℹ 6 more variables: cigarette_butts <dbl>, glass_bottles <dbl>,
    ## #   plastic_bags <dbl>, wrappers <dbl>, homes_powered <dbl>, trash_wheel <chr>

`prof_trash_wheel` is a dataset with 105 dumpsters and 12 variables. the
variables provide information on all of the observed dumpsters which are
labeled by their dumpster number `dumpster` and the date `date`. each
dumpster has recorded measures of their `weight` (measure in tons),
`volume` (measured by cubic yards), specific numbers of each type of
trash they contain, and the number of homes they have powered calculated
by `homes_powered = (weight*500) / 30` since each ton of trash equates
500 kilowatts of energy and an average household uses 30 kilowatts per
day. `dumpter` `103` was removed because it contained multiple `na`
values. the last row of `prof_trash_wheel` was deleted because it was
missing values for `dumpster` and `date`. the variable names were
renamed in order to be easier to read and comprehend. the original
variable columns `month` and `year` were removed since the date is
already provided. the original variable column `homes_powered` was
mutated in order to correctly calculate the number of homes powered by
prof. trash wheel. lastly, a variable column `trash_wheel` was added in
order to specify that these observed dumpsters belong to prof. trash
wheel. the total amount of trash that prof. trash wheel collected is
2.203594^{6}.

### gwynda trash wheel

``` r
gwyn_trash_wheel = 
  readxl::read_excel("data/new_trash_data.xlsx", "Gwynnda Trash Wheel") |> 
  janitor::clean_names() |> 
  drop_na(dumpster) |> 
  rename(weight = weight_tons) |> 
  rename(volume = volume_cubic_yards) |> 
  select(dumpster, date, weight, volume, plastic_bottles, polystyrene, cigarette_butts, plastic_bags, homes_powered) |> 
  mutate(
  homes_powered = (weight*500) / 30 ,
  trash_wheel = "gwynnda trash"
)

gwyn_trash_wheel
```

    ## # A tibble: 155 × 10
    ##    dumpster date                weight volume plastic_bottles polystyrene
    ##       <dbl> <dttm>               <dbl>  <dbl>           <dbl>       <dbl>
    ##  1        1 2021-07-03 00:00:00   0.93     15            1200         360
    ##  2        2 2021-07-07 00:00:00   2.26     15            2000         240
    ##  3        3 2021-07-07 00:00:00   1.62     15            1800         270
    ##  4        4 2021-07-16 00:00:00   1.76     15            1000         180
    ##  5        5 2021-07-30 00:00:00   1.53     15            2100         240
    ##  6        6 2021-08-11 00:00:00   2.06     15            2400         360
    ##  7        7 2021-08-14 00:00:00   1.9      15            2700         320
    ##  8        8 2021-08-16 00:00:00   2.16     15            3000         320
    ##  9        9 2021-08-16 00:00:00   2.6      15             980         180
    ## 10       10 2021-08-17 00:00:00   3.21     15             240          42
    ## # ℹ 145 more rows
    ## # ℹ 4 more variables: cigarette_butts <dbl>, plastic_bags <dbl>,
    ## #   homes_powered <dbl>, trash_wheel <chr>

`gwyn_trash_wheel` is a dataset with 155 dumpsters and 10 variables. the
variables provide information on all of the observed dumpsters which are
labeled by their dumpster number `dumpster` and the date `date`. each
dumpster has recorded measures of their `weight` (measure in tons),
`volume` (measured by cubic yards), specific numbers of each type of
trash they contain, and the number of homes they have powered calculated
by `homes_powered = (weight*500) / 30` since each ton of trash equates
500 kilowatts of energy and an average household uses 30 kilowatts per
day. the second to last row of `gwyn_trash_wheel` was deleted because it
only contained `na` values. the last row of `gwyn_trash_wheel` was
deleted because it was missing its dumpster number and date. a lot of
dumpsters in `gwyn_trash_wheel` were missing values for `wrappers`.
although some of the rows did contain values for `wrappers` I made the
decision to delete this column for the sake of readability and so that
all of the `dumpsters` in `gwyn_trash_wheel` can be fairly compared. the
variable names were renamed in order to be easier to read and
comprehend. the original variable columns `month` and `year` were
removed since the date is already provided. the original variable column
`homes_powered` was mutated in order to correctly calculate the number
of homes powered by gwynda trash wheel. lastly, a variable column
`trash_wheel` was added in order to specify that these observed
dumpsters belong to gwynda trash wheel. there are a few rows to
highlight in `gwyn_trash_wheel`: dumpster numbers `45`, `46`, `85`,
`95`, `96`, and `102` contain all `0` values for pieces of trash which
could indicate periods of zero rainfall which is directly related to the
amount of pollutants. the total number of cigarette butts that gwynda
trash wheel collected in July 2021 is 1.63^{4}.

### combine 3 datasets

``` r
trash_data = 
  bind_rows(mr_trash_wheel, prof_trash_wheel, gwyn_trash_wheel) |> 
  select(dumpster, date, weight, volume, plastic_bottles, polystyrene, cigarette_butts, plastic_bags, homes_powered, trash_wheel)
trash_data
```

    ## # A tibble: 844 × 10
    ##    dumpster date                weight volume plastic_bottles polystyrene
    ##       <dbl> <dttm>               <dbl>  <dbl>           <dbl>       <dbl>
    ##  1        1 2014-05-16 00:00:00   4.31     18            1450        1820
    ##  2        2 2014-05-16 00:00:00   2.74     13            1120        1030
    ##  3        3 2014-05-16 00:00:00   3.45     15            2450        3100
    ##  4        4 2014-05-17 00:00:00   3.1      15            2380        2730
    ##  5        5 2014-05-17 00:00:00   4.06     18             980         870
    ##  6        6 2014-05-20 00:00:00   2.71     13            1430        2140
    ##  7        7 2014-05-21 00:00:00   1.91      8             910        1090
    ##  8        8 2014-05-28 00:00:00   3.7      16            3580        4310
    ##  9        9 2014-06-05 00:00:00   2.52     14            2400        2790
    ## 10       10 2014-06-11 00:00:00   3.76     18            1340        1730
    ## # ℹ 834 more rows
    ## # ℹ 4 more variables: cigarette_butts <dbl>, plastic_bags <dbl>,
    ## #   homes_powered <dbl>, trash_wheel <chr>

`mr_trash_wheel`, `prof_trash_wheel`, and `gwyn_trash_wheel` were
combined in order to compare their data. It is important that the
variable column `trash_wheel` was created in order to differentiate
which dumpster belonged to which wheel. the variables `dumpster`,
`date`, `weight`, `volume`, and `homes_powered` were included because
they give important descriptions of each dumpster. the only trash-type
variables that were kept in the combined dataset were `plastic_bottles`,
`polystyrene`, `cigarette_butts`, and `palstic_bags`, because they were
the only pollutants that were recorded for all three dumpsters. for
example, `sports_balls` was only found in `mr_trash_wheel`, so the
entire column was removed from the combined dataset because there was no
other data to compare it to for the other two dumpsters.

# Problem 3

``` r
mci_baseline_data = read_csv("data/data_mci/MCI_baseline.csv")[-1,] |> 
  janitor::clean_names() |> 
  rename(ID = x1) |> 
  rename(current_age = age_at_the_study_baseline) |> 
  rename(sex = x1_male_0_female) |> 
  rename(education = years_of_education) |> 
  rename(apoe4 = x1_apoe4_carrier_0_apoe4_non_carrier) |> 
  rename(age_at_onset = age_at_the_onset_of_mci_missing_if_a_subject_remains_mci_free_during_the_follow_up_period) |> 
    mutate(
    sex = case_match(
      sex, 
      "0" ~ "male",
      "1" ~ "female"
    )
  ) |> 
    mutate(
    apoe4 = case_match(
      apoe4, 
      "1" ~ "carrier",
      "0" ~ "non-carrier"
    )
  ) |> 
    mutate(
      age_at_onset = as.numeric(as.character(age_at_onset))
    )
```

    ## New names:
    ## Rows: 484 Columns: 6
    ## ── Column specification
    ## ──────────────────────────────────────────────────────── Delimiter: "," chr
    ## (6): ...1, Age at the study baseline, 1 = Male, 0 = Female, Years of edu...
    ## ℹ Use `spec()` to retrieve the full column specification for this data. ℹ
    ## Specify the column types or set `show_col_types = FALSE` to quiet this message.
    ## • `` -> `...1`

    ## Warning: There was 1 warning in `mutate()`.
    ## ℹ In argument: `age_at_onset = as.numeric(as.character(age_at_onset))`.
    ## Caused by warning:
    ## ! NAs introduced by coercion

``` r
baseline_data = drop_na(mci_baseline_data)



amy_data = read_csv("data/data_mci/mci_amyloid.csv")[-1,] |> 
  janitor::clean_names() |> 
  rename(ID = study_id) |> 
  rename(baseline = time_in_years_elapsed_since_the_study_baseline_to_the_visit_where_biomarker_amyloid_42_40_ratio_was_measured) |> 
  rename(time_2 = na_3) |> 
  rename(time_4 = na_4) |> 
  rename(time_6 = na_5) |> 
  rename(time_8 = na_6) |> 
  drop_na(baseline, time_2, time_4, time_6, time_8)
```

    ## New names:
    ## Rows: 488 Columns: 6
    ## ── Column specification
    ## ──────────────────────────────────────────────────────── Delimiter: "," chr
    ## (6): Study ID, Time (in years) elapsed since the study baseline to the v...
    ## ℹ Use `spec()` to retrieve the full column specification for this data. ℹ
    ## Specify the column types or set `show_col_types = FALSE` to quiet this message.
    ## • `NA` -> `NA...3`
    ## • `NA` -> `NA...4`
    ## • `NA` -> `NA...5`
    ## • `NA` -> `NA...6`

``` r
time_2_clean = amy_data[!(amy_data$time_2=="Na"),]
time_4_clean = time_2_clean[!(time_2_clean$time_4=="Na"),]
time_6_clean = time_4_clean[!(time_4_clean$time_6=="Na"),]
time_8_clean = time_6_clean[!(time_6_clean$time_8=="Na"),]
amyloid_data = time_8_clean[!(time_8_clean$baseline=="Na"),]
 

baseline_data
```

    ## # A tibble: 97 × 6
    ##    ID    current_age sex    education apoe4       age_at_onset
    ##    <chr> <chr>       <chr>  <chr>     <chr>              <dbl>
    ##  1 3     62.5        female 16        carrier             66.8
    ##  2 5     66          female 16        non-carrier         68.7
    ##  3 7     66.5        female 18        non-carrier         74  
    ##  4 13    63.1        female 12        carrier             69  
    ##  5 14    58.4        male   20        non-carrier         66.2
    ##  6 18    67.8        female 16        non-carrier         69.8
    ##  7 22    67.3        male   20        carrier             74.6
    ##  8 26    64.8        male   20        carrier             71.1
    ##  9 30    66.3        male   12        non-carrier         73.1
    ## 10 39    68.3        male   16        carrier             70.2
    ## # ℹ 87 more rows

``` r
amyloid_data
```

    ## # A tibble: 340 × 6
    ##    ID    baseline    time_2      time_4      time_6      time_8     
    ##    <chr> <chr>       <chr>       <chr>       <chr>       <chr>      
    ##  1 2     0.107481183 0.109157373 0.109457839 0.105729713 0.10661845 
    ##  2 4     0.109251358 0.108699686 0.110540386 0.107476797 0.111212209
    ##  3 5     0.107950408 0.112273883 0.115139677 0.106606054 0.106052066
    ##  4 6     0.112426974 0.112853415 0.11143945  0.110279277 0.114982747
    ##  5 11    0.109119335 0.109316496 0.1114037   0.108586573 0.108993335
    ##  6 12    0.112042298 0.114167481 0.109859682 0.106842794 0.107334106
    ##  7 13    0.110300505 0.108534417 0.108100808 0.109229662 0.104861901
    ##  8 16    0.110218888 0.113741328 0.111101474 0.108852437 0.109556166
    ##  9 17    0.108399246 0.113317542 0.105909034 0.107196914 0.110199133
    ## 10 18    0.114137255 0.107093264 0.110872562 0.108982605 0.106873903
    ## # ℹ 330 more rows

``` r
merge_data = merge(baseline_data, amyloid_data, by.baseline_data = ID, by.amyloid_data = ID)
merge_data
```

    ##     ID current_age    sex education       apoe4 age_at_onset    baseline
    ## 1  109        66.2   male        16     carrier         68.4 0.107026721
    ## 2  120        64.5   male        20     carrier         72.2 0.106856079
    ## 3  123        64.4 female        18     carrier         67.4 0.108080327
    ## 4   13        63.1 female        12     carrier         69.0 0.110300505
    ## 5  132        63.2 female        16     carrier         66.0  0.10908984
    ## 6  146        62.7   male        16 non-carrier         66.7 0.111194981
    ## 7  149        61.1   male        16     carrier         68.9 0.108500622
    ## 8  170        65.6 female        16 non-carrier         70.7  0.11478716
    ## 9  177        67.4   male        16     carrier         74.4 0.107080076
    ## 10  18        67.8 female        16 non-carrier         69.8 0.114137255
    ## 11 202        70.1   male        18     carrier         75.2 0.108924204
    ## 12 218        61.2 female        16 non-carrier         65.9  0.11380286
    ## 13 226        70.4 female        16 non-carrier         75.4 0.113086843
    ## 14 229        65.6   male        18 non-carrier         70.9 0.110090355
    ## 15 234        66.7 female        18 non-carrier         66.7 0.110521689
    ## 16 242        68.1 female        12 non-carrier         75.6 0.110615293
    ## 17 249        64.5   male        16     carrier         68.4 0.107875226
    ## 18 250        68.1 female        16     carrier         74.5 0.107287702
    ## 19 252        66.2 female        16     carrier         69.6 0.106002663
    ## 20  26        64.8   male        20     carrier         71.1 0.104749004
    ## 21 283          69 female        16 non-carrier         68.3 0.113436336
    ## 22 287          63 female        16     carrier         68.0 0.108545195
    ## 23 292        66.1   male        18 non-carrier         70.2 0.112005473
    ## 24 297        67.3 female        16     carrier         73.9 0.112519791
    ## 25  30        66.3   male        12 non-carrier         73.1 0.109311868
    ## 26 305          70   male        18     carrier         77.2 0.106575146
    ## 27 306        69.5   male        16 non-carrier         72.6 0.107617927
    ## 28 314          63   male        16 non-carrier         68.7 0.114488695
    ## 29 323        67.4   male        16     carrier         73.9 0.108951493
    ## 30 328        65.5 female        16 non-carrier         71.0 0.116053343
    ## 31 336        67.2   male        16     carrier         73.7 0.105515499
    ## 32 337        67.8   male        16 non-carrier         75.0 0.110234919
    ## 33 338          65   male        16 non-carrier         70.8 0.113154484
    ## 34 347        67.7 female        16     carrier         68.9 0.106142357
    ## 35 348        64.4 female        16     carrier         70.4 0.108953572
    ## 36 350        70.7   male        16     carrier         75.2 0.104448098
    ## 37 351        69.4 female        16     carrier         76.6 0.109113066
    ## 38 365        64.5   male        16 non-carrier         67.7 0.108368155
    ## 39 366        66.8 female        16     carrier         72.8 0.109407468
    ## 40 369        63.3 female        18     carrier         68.6 0.111860082
    ## 41 373        62.5 female        16 non-carrier         66.0  0.11218911
    ## 42 377        65.4   male        16     carrier         68.2 0.108737385
    ## 43 380        70.3   male        16 non-carrier         70.2 0.111158847
    ## 44 408        64.1 female        20     carrier         70.2 0.110779441
    ## 45 409        69.3 female        16     carrier         75.2 0.109306118
    ## 46 416        66.6   male        16 non-carrier         68.9 0.111767429
    ## 47 417        68.1   male        16     carrier         72.5 0.109277104
    ## 48 419        60.7   male        16     carrier         63.8 0.114644146
    ## 49 423        64.8   male        16     carrier         70.3 0.108118705
    ## 50 426        69.8 female        16 non-carrier         76.8 0.110310062
    ## 51 431        58.9 female        16     carrier         61.2 0.117180111
    ## 52 442        70.3 female        18 non-carrier         71.3 0.107946154
    ## 53  45        62.9 female        20     carrier         65.2 0.106887426
    ## 54 453        62.7 female        18 non-carrier         68.6 0.113857033
    ## 55 471        62.6 female        16     carrier         68.9 0.111027383
    ## 56   5          66 female        16 non-carrier         68.7 0.107950408
    ## 57  55        69.3   male        16     carrier         73.6 0.101507799
    ## 58  59        66.7   male        20     carrier         74.4 0.103415696
    ## 59  65        62.8   male        16 non-carrier         66.5  0.11256305
    ## 60  69        65.5   male        20     carrier         72.5 0.114392996
    ## 61  75        61.2   male        16     carrier         65.4 0.108368094
    ## 62  76        65.9 female        12 non-carrier         68.0 0.110931307
    ## 63  77        63.7   male        18     carrier         66.4 0.107284617
    ## 64  78          65 female        16 non-carrier         68.0 0.113982537
    ## 65  86          66   male        18     carrier         71.7 0.108360583
    ## 66  87        68.2 female        18 non-carrier         76.0 0.113658986
    ##         time_2      time_4      time_6      time_8
    ## 1  0.107718021 0.104457501 0.100723304 0.100848092
    ## 2  0.111398319 0.103014244 0.106365255 0.103045743
    ## 3  0.112383506  0.11008691 0.107630692 0.101780509
    ## 4  0.108534417 0.108100808 0.109229662 0.104861901
    ## 5  0.108979186 0.106198191 0.105698988 0.102579378
    ## 6  0.111374948 0.113454429 0.109239435 0.108603552
    ## 7  0.110531747 0.110113935 0.106510401 0.106897608
    ## 8  0.111734748 0.111511576 0.113622709  0.11056932
    ## 9  0.103880457 0.104338764 0.106399715 0.102465143
    ## 10 0.107093264 0.110872562 0.108982605 0.106873903
    ## 11 0.103006361 0.103228003 0.102029846 0.100056292
    ## 12 0.115676631 0.112240869 0.110319531 0.110548777
    ## 13 0.110028856 0.110193695 0.107221396 0.105330637
    ## 14 0.114248533 0.111349647 0.107372297 0.108299128
    ## 15 0.110988335 0.110318671 0.107334344 0.108868811
    ## 16 0.112466023 0.110543716 0.108457735 0.106649029
    ## 17 0.106120934 0.110522028  0.10443051 0.104297366
    ## 18 0.109043837 0.109596383 0.105458715  0.10294026
    ## 19 0.109438988 0.104734598 0.108832219 0.105513741
    ## 20 0.110171403 0.106128029 0.102036973 0.104994305
    ## 21 0.106568976  0.11338643  0.10820706 0.114399611
    ## 22 0.109804562 0.112595781 0.109277394 0.107288238
    ## 23 0.111128689 0.110529628 0.107524069 0.111213884
    ## 24 0.107296829 0.109572724 0.107416099 0.105536131
    ## 25 0.111327152 0.107454368 0.113914306 0.108895642
    ## 26 0.109139729 0.107237307 0.100797063 0.103960862
    ## 27  0.10549774 0.105779618 0.104030737 0.103597858
    ## 28 0.111534036 0.113995497 0.116064016 0.111072404
    ## 29 0.108156014 0.107161066 0.107789675 0.103367206
    ## 30 0.108732458 0.107981127 0.110412399 0.107545571
    ## 31 0.105559957 0.102679883  0.10569702  0.10640764
    ## 32 0.109115569 0.110457079 0.111424351 0.109695757
    ## 33 0.113866071 0.107875179 0.109168346 0.110056896
    ## 34 0.105404684 0.106038639 0.104798607 0.102539751
    ## 35 0.109108861  0.10913821 0.111055899 0.111664612
    ## 36 0.106251499 0.109105546 0.105341362 0.102666049
    ## 37 0.110681827 0.104622912 0.107114993  0.10775628
    ## 38  0.11282099 0.109700177 0.103664695 0.104995131
    ## 39 0.110142355 0.108078589 0.104223474 0.103784985
    ## 40 0.104362159 0.112709888 0.107915913 0.107131432
    ## 41 0.117060394 0.113077811 0.116411516 0.106141346
    ## 42 0.107877634 0.107528215 0.105783551 0.104676513
    ## 43 0.104560429 0.106822683 0.104961175 0.109506164
    ## 44  0.11081594 0.111759647  0.10560759  0.11096394
    ## 45 0.109355444 0.104203305 0.104801719 0.104392625
    ## 46 0.109024281 0.113209208 0.105000017 0.106021985
    ## 47  0.10508806 0.105360371 0.105517925  0.10132809
    ## 48 0.108243592 0.112268963 0.106069914  0.10415295
    ## 49 0.107796862 0.107986282 0.103578995  0.11011534
    ## 50 0.106626194 0.105759193 0.108039787 0.105913739
    ## 51 0.110687702 0.107133996  0.10872562 0.106799552
    ## 52 0.114161562   0.1105537 0.106454629 0.103088929
    ## 53 0.110818579 0.111516749 0.107179289  0.10457923
    ## 54 0.112321772 0.108314519 0.109028408 0.106029713
    ## 55 0.106424715 0.111068422 0.107208238 0.110534005
    ## 56 0.112273883 0.115139677 0.106606054 0.106052066
    ## 57 0.105455229 0.104251537 0.106088762 0.103609078
    ## 58  0.10351346 0.100971886 0.108515848 0.104119779
    ## 59  0.11366025 0.112475164 0.111539121 0.111844573
    ## 60 0.104970251 0.109161136 0.107839858 0.107005326
    ## 61  0.10773377 0.105117512 0.106359342 0.105999842
    ## 62 0.109048068 0.106670279  0.10805051 0.111364424
    ## 63 0.106476261 0.112886515 0.101454474  0.10454377
    ## 64 0.110739736 0.113457585 0.111259357 0.108290955
    ## 65 0.102932875 0.106523976 0.104131568 0.101939043
    ## 66 0.110688998 0.112175174 0.107445684 0.103597297

``` r
write.csv(merge_data, "data/data_mci/merge_data.csv", row.names=FALSE)
```

`baseline_data` is a dataset with 97 patients and 6 variables. the
variables include important demographics about each patient but most
importantly specify in `apoe4` whether they are a carrier of the gene
variant or not. many of the original variables were renamed to be more
descriptive and easier to read and comprehend such as `x1` being renamed
to `ID` in order to represent the patient ID. other original variable
names were too long and were shortened such as
`age_at_onset_of_mci_missing_if_a_subject_remains_mci_free_during_the_follow_up_period`
being renamed to `age_at_onset`. the values in the `sex` column were
mutated in order to be easier to understand their meaning. originally,
all of the values were either `0` or `1`. the values were mutated with
the conditions `0 ~ male` and `1 ~ female` so that the values in the
final dataset appear as `male` and `female` instead of numeric values.
similarly, the values in `apoe4` were mutated in order to be easier to
understand their meaning. originally, all of the values were either `0`
or `1`. the values were mutated with the conditions `1 ~ carrier` and
`0 ~ non-carrier` so that the values in the final dataset appear as
`carrier` and `non-carrier` instead of numeric values. all of the values
in `age_at_onset` had to be mutated from character values to numeric
using `mutate` and `as.numeric`. finally, all patients with any missing
values were removed completely by using `drop_na`. 483 patients were
recruited, but only 97 patients developed MCI. because the values of
`age_at_onset` were converted to numeric values, the average baseline
age was able to be calculated: 70.2628866. The ratio of women who are
carriers of the apoe4 mutation is 31 out of 51.

`amyloid_data` is a data set with 340 patients and 6 variables. the
variables provide the patient ID and baseline (time in years elapsed
since the study baseline to the visit where biomarker amyloid 42/40
ratio was measured), and then records the ratio at 4 different time
markers denoted by `time_2`, `time_4`, `time_6`, and `time_8`. the first
row of the data was removed because it only contained the descriptions
of the different variables. some of the variables were renamed in order
to be shorter and easier to read and comprehend. for example,
`time_in_years_elapsed_since_the_study_baseline_to_the_visit_where_biomarker_amyloid_42_40_ratio_was_measured`
was renamed `baseline`. the time marker variables were also renamed from
`na_#` to `time_#`. all of the rows that contained any value `na` was
removed. there were originally 495 patients recruited, but only the data
from 340 patients exist in the final dataset.

`baseline_data` and `amyloid_data` were merged to create `merge_data`
that only contains the data from patients who exist in both datasets.
there are a lot of patients who exist only in `baseline_data` or only in
`amyloid_data` meaning they must have had some missing value in one of
the datasets. for example, patient 3 exists in `baseline_data` since
they have all of their demographics and initial measurements, but does
not exist in `amyloid_data` due to a missing value for `time_6`. there
are 97 patients in `baseline_data` and 340 patients in `amyloid_data`.
however, only 66 patients exist in `merge_data`. `merge_data` is
important for data analysis because it shows the patients demographics
compared to their carrier status and ratio recordings.
